### ISSUE TITLE
ES 6 module?

### ISSUE THREAD

**Issue by KayakinKoder** [crypto-browserify/randombytes#12]
Pardon my javascript naivety -- is there an es 6 module version of randombytes? Rollupjs has an issue with either crypto or buffer shims I think, and just isn't playing nicely in the browser. Thanks for very useful set up plugins btw, has worked great in my other webpack projects.

**Comment by dcousens** [comment]
> Rollupjs has an issue with either crypto or buffer shims I think

I'd focus on this,  not on this module.  :+1:

**Comment by calvinmetcalf** [comment]
its crypto some of the elliptical curve stuff doesn't play well if I recal

**Comment by KayakinKoder** [comment]
@dcousens yes they are aware, was just wondering on your end if there was an es 6 module available. Thanks again

**Comment by dcousens** [comment]
@KayakinKoder you could ES6/babel your exports,  then deal with them that way?
Maybe?
