### ISSUE TITLE
requested too many random bytes

### ISSUE THREAD

**Issue by achingbrain** [crypto-browserify/randombytes#14]
It looks like this library limits the number of random bytes you can request to [65536](https://github.com/crypto-browserify/randombytes/blob/master/browser.js#L18).  Node limits it to the [max value of an unsigned 32 bit integer](https://github.com/nodejs/node/blob/master/lib/internal/crypto/random.js#L52).

Is there any reason for the discrepancy?

**Comment by calvinmetcalf** [comment]
yes that's the limit of [getRandomValues](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues), the browser api we use

**Comment by achingbrain** [comment]
I see - why not request multiples of 65536 and join the buffers together?

**Comment by dcousens** [comment]
@achingbrain PR accepted I suppose

**Comment by robyoder** [comment]
This should have been closed by #16 I believe.
