### ISSUE TITLE
Hi, is it secure to use crypto random bytes to generate both access token and refresh token?

### ISSUE THREAD

**Issue by kev1ee** [crypto-browserify/randombytes#23]
## Question
Hi, is it secure to use crypto random bytes to generate both access token and refresh token for custom authentication?

**Comment by calvinmetcalf** [comment]
if you have a library that is used both in the browser and in node then yes this is a good option to use, if you are just targeting just the browser or just node it's probably better to  directly use         crypto.getRandomValues or crypto.randomBytes respectively

**Comment by kev1ee** [comment]
@calvinmetcalf Thanks :)
