### ISSUE TITLE
Fails for me as Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by frozeman** [crypto-browserify/randombytes#5]
You check for the crypto object one `global` not on `window` and therefore fails for me when used as a dependency in another project. Why using `global`?

**Comment by frozeman** [comment]
And if this is something specific to browserify, how i make this package work in vanilla js?

**Comment by calvinmetcalf** [comment]
`var global = window;`

**Comment by frozeman** [comment]
Yeah this will break a lot of other dependencies which use the presence of `global` to determine  wether they are in a node or browser in env.

**Comment by calvinmetcalf** [comment]
you could use it with browserify like it's intended, or you could just modify the version you are using to work in the specific environment you are using it in

**Comment by frozeman** [comment]
Yeah i build my own: https://github.com/frozeman/randomHex

**Comment by calvinmetcalf** [comment]
there is no actual code in that repo fyi

**Comment by frozeman** [comment]
? Maybe i dint pushed by then, but there is now :P

**Comment by jvlad** [comment]
@frozeman thanks, maybe. But now there isn't:)
It looks like some relevant files were removed from the repo work dir in this commit: https://github.com/frozeman/randomHex/commit/cd6a244b84e42a0d166a746ac5ba542065b16e87#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346
