### ISSUE TITLE
 secure random number generation not supported by this browser use chrome, FireFox or Internet Explorer 11

### ISSUE THREAD

**Issue by omryr** [crypto-browserify/randombytes#6]
im using a library that is using this one and im getting this error when running in IE 11, did anyone encounter it? and if yes what was the solution? i am looking for a few hours now and kinda lost, would appreciate any help.
thanks!

**Comment by calvinmetcalf** [comment]
that's really strange because IE11 supports it, what library are you using that is relying on it and what is the exact version of that library and IE are you using

**Comment by omryr** [comment]
im using etereumjs-wallet library

**Comment by calvinmetcalf** [comment]
using it where?

**Comment by omryr** [comment]
in a client side application

**Comment by calvinmetcalf** [comment]
in a browser? if so which one?

**Comment by omryr** [comment]
it happens to me in explorer 11 and also safari on ipads

**Comment by calvinmetcalf** [comment]
other discussion ethereumjs/ethereumjs-wallet#15

what are you using to bundle the app, does it work in chrome ?

**Comment by therightstuff** [comment]
if you're looking for crypto library compatible keys, take a look at https://gist.github.com/therightstuff/84ae710c3c301fe7979d7f0aa9c7c147 - i initially used aes-js and md5 on the client, but i now use the browserified crypto library; there was no need to modify the generateSessionKeys function.

**Comment by calvinmetcalf** [comment]
@therightstuff the interesting thing is just that that error shouldn't be coming up at all here so there is likely something weird going on in like a bundler or something

**Comment by omryr** [comment]
im using "webpack": "^2.3.3"

**Comment by omryr** [comment]
and yes it works in chrome and mosly works in safari, IE it doesnt work at all

**Comment by calvinmetcalf** [comment]
what version of IE, exactly ?

**Comment by omryr** [comment]
im trying IE 11 atm

**Comment by calvinmetcalf** [comment]
ok and if it doesn't work then the full version number would be helpful

**Comment by omryr** [comment]
IE 11.0.15063.0 is the version im running

**Comment by dcousens** [comment]
Verdict?

**Comment by calvinmetcalf** [comment]
I have no clue, I'm not able to reproduce

**Comment by bokub** [comment]
Same problem with both **IE 11.786.15063.0** and **Firefox 47.0.2**.

I'm using a webpack version 14.5.0 + babel 6.26.0.

Here is the generated code: 

```js
    var Buffer = require('safe-buffer').Buffer;
    var crypto = global.crypto || global.msCrypto;
    if (crypto && crypto.getRandomValues) {
        module.exports = randomBytes;
    } else {
        module.exports = oldBrowser;
    }
```
Both `global.crypto` and `global.msCrypto` are undefined.

**Comment by calvinmetcalf** [comment]
is have you configured babel or webpack not to include `global` ?

**Comment by bokub** [comment]
EDIT: it was not **webpack** version 14.5.0 but browserify version 14.5.0.

And no, I don't know how to do this, but I'll look

**Comment by calvinmetcalf** [comment]
are window.crypto and window.msCrypto also undefined and does global === window ?

**Comment by bokub** [comment]
`window` is undefined because my code is in a web worker. However, `global` is equal to the [WorkerGlobalScope](https://developer.mozilla.org/fr/docs/Web/API/WorkerGlobalScope)

**Comment by calvinmetcalf** [comment]
oh yeah `getRandomValues` isn't available in a web worker

**Comment by bokub** [comment]
Works with chrome and recent Firefox versions though.. 

Thanks for your help :+1:

**Comment by MaxMillington** [comment]
I'm getting this error in IE10. Does `randombytes` not support IE10?

**Comment by Hema1Latha** [comment]
iam using web3 library iam getting the same error can anyone help me to fix this

**Comment by calvinmetcalf** [comment]
that is correct

**Comment by AilsonEsi** [comment]
hi guys, some one can help me, so im trying to create a project i had same error, im using linux mint, what can i do to solve this?

**Comment by calvinmetcalf** [comment]
@AilsonEsi what browser and version are you using, and are you trying to use it in a web worker?

**Comment by xperiafan13-rom** [comment]
some here

**Comment by calvinmetcalf** [comment]
folks, are you in a web worker? if so browsers don't support it, maybe we need a more explicit error when you try to use this in a web worker?
