### ISSUE TITLE
Buffer.from is not a function

### ISSUE THREAD

**Issue by kjvalencik** [crypto-browserify/randombytes#9]
[This commit](https://github.com/crypto-browserify/randombytes/commit/800369c0f80dd22e3d720cf60d977c8e9a767b95) introduced a regression in browsers that don't implement `Buffer.from`.

**Comment by jprichardson** [comment]
Please update your dependencies. `safe-buffer` provides a compatible shim for `Buffer.from`.

**Comment by kjvalencik** [comment]
Interesting. I see that. It might be that some part of the processing pipeline is removing the `if` statement based on the Node buffer implementation. `safe-buffer` has been trimmed to just `module.exports = require('buffer')` in the build.

**Comment by calvinmetcalf** [comment]
@kjvalencik that *was* the case until the most recent version of safe-buffer fixed that

**Comment by calvinmetcalf** [comment]
@kjvalencik that *was* the case until the most recent version of safe-buffer fixed that

**Comment by kjvalencik** [comment]
@calvinmetcalf Thanks. That is confirmed the issue. I bumped the version and it fixed it.

**Comment by calvinmetcalf** [comment]
published

**Comment by calvinmetcalf** [comment]
published v2.0.5
